fail_fast: true
repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: go-imports
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: go-mod-tidy
      - id: go-build