name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Install pre-commit dependencies
        run: |
          go get github.com/fzipp/gocyclo
          go get golang.org/x/tools/cmd/goimports
          go get github.com/go-critic/go-critic/cmd/gocritic
          go get golang.org/x/lint/golint
          go get github.com/BurntSushi/toml/cmd/tomlv
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v ./test/...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

